### PR TITLE
bump: llvm from 13 to 14

### PR DESCRIPTION
**Pull request by baszalmstra**
Bump LLVM from 13 to 14.

### CODE REVIEW

**Review by Wodann — APPROVED** [review]

**Review by Wodann — COMMENTED** [review]
Just make sure to also add a changelog :)

**Comment by baszalmstra** [comment]
Thanks I modified the changelog. 

To get this to work on macOS I had to refactor the apple targets again a little bit. I think they are actually simpler now. It works on my old x86_64 MacBook but I don't have access to an M1. Would you be able to run the tests locally @Wodann ?

**Comment by Wodann** [comment]
> To get this to work on macOS I had to refactor the apple targets again a little bit. I think they are actually simpler now. It works on my old x86_64 MacBook but I don't have access to an M1. Would you be able to run the tests locally @Wodann ?

Yup, I'll checkout your branch and run it 🙂

**Review by Wodann — COMMENTED** [review]
Works on my M1 and LGTM!

**Comment by baszalmstra** [comment]
I released lld-rs for LLD 14 and updated the dependency in this branch. If CI succeeds we can merge.

**Pull request merged**
