### PR TITLE
refactor: renamed `public` to `pub` and removed some un-used functions

### PR DESCRIPTION
**Pull request by tdejager**

### CODE REVIEW

**Comment by baszalmstra** [comment]
Can you squash both commits into one and rebase onto master? After that I can incorporate them.

**Comment by baszalmstra** [comment]
@tdejager could you take another look at this?

**Comment by Wodann** [comment]
Hi @tdejager, I am planning on using `pub` in structs (PR #64) so would like to incorporate this PR. Do you have time to rebase this PR with the latest master and update the PR for review?

**Comment by tdejager** [comment]
Brought this brach up-to-date with master again

**Comment by baszalmstra** [comment]
@tdejager Could you squash and rebase this PR so we can "rebase and merge" it into master? It's currently still showing conflicts. Running:
```
git rebase master
```
will show you what exactly.

**Comment by tdejager** [comment]
> @tdejager Could you squash and rebase this PR so we can "rebase and merge" it into master? It's currently still showing conflicts. Running:
> 
> ```
> git rebase master
> ```
> 
> will show you what exactly.

Sorry, but I've used a regular merge. Even when squashing my commits, I don't think it matters I have to solve a merge conflict for an unkown number of commits. I stopped rebasing after about fixing 8 commits..

**Pull request merged**
